config/routes.rb
AcaRails::Engine.routes.draw do

  root :to => "home#index"
  get '/home/index'
  get '/locked' => 'home#locked'

  get "/logout" => "sessions#destroy", :as => "logout"
  get "/login" => "sessions#new", :as => "login"
  post "/login" => "sessions#create"

  resources :users do
    collection { get :versions }
  end
  get 'users/:id/version' => 'users#version', as: :version_user

  resources :changepwds
  resources :my_profile
  resources :inactivate
  resources :password_resets

  get '/signup' => 'signup#new'
  post '/signup' => 'signup#create'
  get '/signup/:id/edit' => 'signup#edit', as: :confirm_email
  put '/signup/:id' => 'signup#update'
  patch '/signup/:id' => 'signup#update'

  get "/401", to: "errors#unauthorized"
  get "/403", to: "errors#forbidden"
  get "/404", to: "errors#not_found"
  get "/405", to: "errors#method_not_allowed"
  get "/500", to: "errors#server_error"

end

app/models/aca_rails/application_record.rb
module AcaRails
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/aca_rails/user_version.rb
module AcaRails
  class UserVersion < PaperTrail::Version
    self.table_name = :aca_rails_user_versions
#    belongs_to :user, foreign_key: :whodunnit ##if using a user table, to record who made the change

  end
end

app/controllers/aca_rails/application_controller.rb
module AcaRails
  class ApplicationController < ::ApplicationController
    #ActionController::Base
    protect_from_forgery with: :exception

    before_filter :update_activity_time

    if AcaRails.use_paper_trail
      before_action :set_paper_trail_whodunnit
    end

    def login_required
      if !session[:uid]
        kill_session
        session[:return_to] = request.url
        redirect_to login_path, alert: 'Please login to continue'
      else
        if AcaRails.expire_session_per_time && AcaRails.minutes_to_expire_session.minutes > 1
          session_expiry
        end
      end
    end

    def admin_required
      login_required
      if current_user
        return true
      else
        return unauthorized
        #return false
      end
    end

    def user_can_signup
      if AcaRails.user_can_signup
        return true
      else
        return method_not_allowed
      end
    end

    def user_can_inactivate
      if AcaRails.user_can_inactivate_account
        return true
      else
        return method_not_allowed
      end
    end

    def user_can_delete
      if AcaRails.user_can_delete_account
        return true
      else
        return method_not_allowed
      end
    end

    def user_can_be_deleted
      if AcaRails.user_can_have_account_deleted
        return true
      else
        return method_not_allowed
      end
    end

    def use_forgotten_pwd
      if AcaRails.use_forgotten_password
        return true
      else
        return method_not_allowed
      end
    end

    def user_confirm_email
      if AcaRails.user_confirm_signup_by_email
        return true
      else
        return method_not_allowed
      end
    end

    def kill_session
      session[:uid] = nil
      session[:lgtm] = nil
      session[:cip] = nil

      cookies.delete(:auth_token)
    end

    def session_expiry
      if (session[:expires_at].to_i - Time.now.to_i).to_i < 0
        kill_session
        redirect_to login_path, alert: 'Your session has timed out. Please log back in.'
      end
    end

    def update_activity_time
      begin
        if AcaRails.minutes_to_expire_session.minutes > 1 && AcaRails.expire_session_per_time
          if session[:expires_at_new]
            session[:expires_at] = session[:expires_at_new]
          else
            session[:expires_at] = (Time.now + AcaRails.minutes_to_expire_session.minutes).to_i
          end

          session[:expires_at_new] = (Time.now + AcaRails.minutes_to_expire_session.minutes).to_i
        end
      rescue
        flash[:error] = 'Session timout needs to be configured properly. Please contact system admin.'
      end
    end

    private

    def current_user
      #if cookies[:auth_token]
      #  @current_user ||= User.find_by_auth_token(cookies[:auth_token])
      #elsif session[:uid]
      #  @current_user ||= User.find(session[:uid])
      #else
      #  @current_user = nil
      #end
#      @current_user ||= User.find_by_auth_token(cookies[:auth_token])
      begin
        #@current_user ||= User.find(session[:uid]) if session[:uid]
        @current_user ||= User.find_by_auth_token(cookies[:auth_token])
      rescue
        kill_session
      end

    end

    helper_method :current_user

    protected

    def unauthorized
      render status: 401, template: "/aca_rails/errors/unauthorized.html.erb"
      false
    end

    def forbidden
      render status: 403, template: "/aca_rails/errors/forbidden.html.erb"
      false
    end

    def not_found
      render status: 404, template: "/aca_rails/errors/not_found.html.erb"
      false
      end

    def method_not_allowed
      render status: 405, template: "/aca_rails/errors/method_not_allowed.html.erb"
      false
    end

  end
end

app/controllers/aca_rails/changepwds_controller.rb
require_dependency "aca_rails/application_controller"

module AcaRails
  class ChangepwdsController < ApplicationController
    before_filter :login_required

    def edit
      @user = current_user
    end

    def update
      @user = User.find(params[:id])
      if @user && @user.authenticate(params[:old_password])
        @user.updating_password = true
        respond_to do |format|
          if @user.update_attributes(params[:user].permit(:password, :password_confirmation))
            format.html { redirect_to root_url, notice: 'User was successfully updated.' }
            format.json { head :no_content }
          else
            format.html { render action: "edit" }
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        end
      else
        respond_to do |format|
          flash[:warning] = "Wrong password"
          format.html { render action: "edit", message: 'Wrong password' }
        end
      end
    end

  end
end

app/controllers/aca_rails/home_controller.rb
require_dependency "aca_rails/application_controller"

module AcaRails
  class HomeController < ApplicationController
    def index
    end

    def locked

    end
  end
end

app/controllers/aca_rails/inactivate_controller.rb
require_dependency "aca_rails/application_controller"

module AcaRails
  class InactivateController < ApplicationController

    before_action :user_can_inactivate, only: [:edit, :update]
    before_action :user_can_delete, only: [:destroy]
    before_filter :login_required

    def edit
      @user = current_user
    end

    def update
      @user = User.find(params[:id])

      respond_to do |format|
        if @user.update_attributes(params[:user].permit(:is_active))
              kill_session
              format.html { redirect_to login_path , notice: 'Account successfully inactivated.' }
              format.json { head :no_content }
        else
              format.html { render action: "edit" }
              format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @user = current_user
      @user.destroy
      kill_session
      redirect_to login_path, notice: 'User was successfully destroyed.'
    end

  end
end

app/controllers/aca_rails/my_profile_controller.rb
require_dependency "aca_rails/application_controller"

module AcaRails
  class MyProfileController < ApplicationController
    before_filter :login_required

    def edit
      @user = current_user
    end

    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to root_url, notice: 'Your profile was successfully updated.'
      else
        render :edit
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :login, :email)
    end

  end
end

app/controllers/aca_rails/password_resets_controller.rb
require_dependency "aca_rails/application_controller"

module AcaRails
  class PasswordResetsController < ApplicationController
    before_action :use_forgotten_pwd, only: [:new, :create, :edit, :update]

    def index
      @q = User.ransack(params[:q])
      @users = @q.result(distinct: true).page params[:page]
    end

    def new

    end

    def create
      p = params[:email] || params[:user][:email]
      user = User.find_by_email(p)

      if user
        user.send_password_reset
        redirect_to password_resets_path, :notice => "Email sent with password reset instructions."
      else
        redirect_to login_path, :alert => "Email not registered. Password reset email not sent."
      end

    end

    def edit
      begin
        @user = User.find_by_password_reset_token!(params[:id])
      rescue
        redirect_to login_path, alert: "Password reset has expired, or wrong url."
      end

    end

    def update
      @user = User.find_by_password_reset_token!(params[:id])
      #@user.updating_password = true
      if @user.password_reset_sent_at < 2.hours.ago
        redirect_to new_password_reset_path, :alert => "Password reset has expired."
      elsif @user.update_attributes(user_params)
        redirect_to login_url, :notice => "Password has been reset."
      else
        render :edit
      end
    end

    private
    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end


  end
end

app/controllers/aca_rails/sessions_controller.rb
require_dependency "aca_rails/application_controller"

module AcaRails
  class SessionsController < ApplicationController

    def new
      session[:uid] = nil
      session[:lgtm] = nil
    end

    def create
      if (params[:login] != nil)

        user = User.find_by_email(params[:login][:email])
        if (user && user.aca_authenticate(params[:login][:password], request.remote_ip))
          session[:uid] = user.id
          session[:lgtm] = Time.now
          session[:cip] = request.remote_ip

          if params[:login][:remember_me]
            cookies.permanent[:auth_token] = user.auth_token
          else
            cookies[:auth_token] = user.auth_token
          end

          redirect_to after_sign_up_path #root_url(:notice => "You are now logged in!")
        else
          if user && (user.is_locked? || !user.is_active?)
            flash[:error] = "Account is blocked, contact system admin."
            redirect_to locked_path
          elsif user && !user.is_email_confirmed? && AcaRails.user_confirm_signup_by_email
            flash[:error] = "Please confirm your email."
            redirect_to login_path
          else
            flash[:error] = "Invalid email/login or password"

            redirect_to :action => 'new'
          end
        end

      else
        redirect_to root_url, :error => "Please contact your system administrator. Error: Login parameters"
      end
    end

    def destroy
      kill_session

      redirect_to after_log_out_path
    end

    def after_sign_up_path
      root_url(:notice => "You are now logged in!")
    end

    def after_log_out_path
      login_path(:notice => "You have logged out!")
    end
  end
end

app/controllers/aca_rails/signup_controller.rb
require_dependency "aca_rails/application_controller"

module AcaRails
  class SignupController < ApplicationController

    before_action :user_can_signup
    before_action :user_confirm_email, only: [:edit]

    def new
      @user = User.new
    end

    # POST /users
    def create
      params[:user][:is_admin] = false
      params[:user][:is_active] = true

      @user = User.new(user_params)

      if @user.save
        redirect_to login_path, notice: 'User was successfully created. Please login now!'
      else
        render :new
      end
    end

    def edit
      @user = User.find(params[:id])
      if @user
        @user.confirm_email
      end
    end

    private
    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :login, :email, :password, :password_confirmation, :is_admin, :is_active)
    end
  end
end

app/controllers/aca_rails/users_controller.rb
require_dependency "aca_rails/application_controller"

module AcaRails
  class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :user_can_be_deleted, only: [:destroy]
    before_filter :login_required
    before_filter :admin_required

    # GET /users
    def index
      # @users = User.all
      @q = User.ransack(params[:q])
      @users = @q.result(distinct: true).page params[:page]
    end

    # GET /users/1
    def show
    end

    # GET /users/new
    def new
      @user = User.new
    end

    # GET /users/1/edit
    def edit
    end

    # POST /users
    def create
      @user = User.new(user_params)

      if @user.save
        redirect_to users_path, notice: 'User was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /users/1
    def update
      if @user.update(user_params)
        redirect_to users_path, notice: 'User was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /users/1
    def destroy
      @user.destroy
      redirect_to users_path, notice: 'User was successfully destroyed.'
    end

    def versions
      #@versions = UserVersion.all.order('created_at desc').page params[:page]
      @q = UserVersion.ransack(params[:q])
      @versions = @q.result(distinct: true).order('id desc').page params[:page]

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @versions }
      end
    end

    def version
      if params[:q]== nil
        params[:q] = { item_id_eq: params[:id] }
      else
        params[:q].merge({ item_id_eq: params[:id] })
      end
      @q = UserVersion.ransack(params[:q])
      @versions = @q.result(distinct: true).order('id desc').page params[:page]

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @versions }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def user_params
        params.require(:user).permit(:name, :login, :email, :password, :password_confirmation, :is_admin, :is_active, :last_login, :last_ip, :login_attempts)
      end

      def sort_column
        User.column_names.include?(params[:sort]) ? params[:sort] : "name"
      end

      def sort_direction
        %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
      end

    end
end

app/helpers/aca_rails/application_helper.rb
module AcaRails
  module ApplicationHelper

    def alert_class_for(flash_type)
      {
          :success => 'alert-success',
          :error => 'alert-danger',
          :alert => 'alert-warning',
          :notice => 'alert-info'
      }[flash_type.to_sym] || flash_type.to_s
    end
    
  end
end

app/helpers/aca_rails/changepwds_helper.rb
module AcaRails
  module ChangepwdsHelper
  end
end

app/helpers/aca_rails/home_helper.rb
module AcaRails
  module HomeHelper
  end
end

app/helpers/aca_rails/inactivate_helper.rb
module AcaRails
  module InactivateHelper
  end
end

app/helpers/aca_rails/my_profile_helper.rb
module AcaRails
  module MyProfileHelper
  end
end

app/helpers/aca_rails/password_resets_helper.rb
module AcaRails
  module PasswordResetsHelper
  end
end

app/helpers/aca_rails/sessions_helper.rb
module AcaRails
  module SessionsHelper
  end
end

app/helpers/aca_rails/signup_helper.rb
module AcaRails
  module SignupHelper
  end
end

app/views/layouts/aca_rails/_actions.html.erb
<% if defined?(link_to_show) && link_to_show %>
  <%= link_to link_to_show, :class => 'btn btn-secondary btn-sm', title: "Show", data: { toggle: 'tooltip', placement: 'top' } do%>
      <i class="fa fa-eye-slash"></i>
  <% end %>
<% end %>

<% if defined?(link_to_edit) && link_to_edit %>
  <%= link_to link_to_edit, :class => 'btn btn-primary btn-sm', title: "Edit", data: { toggle: 'tooltip', placement: 'top' } do%>
      <i class="fa fa-edit"></i>
  <% end %>
<% end %>

<% if defined?(link_to_delete) && link_to_delete %>
  <%= link_to link_to_delete, method: :delete, title: "Delete", data: { confirm: 'Are you sure?', toggle: 'tooltip', placement: 'top' }, :class => 'btn btn-danger btn-sm' do %>
      <i class="fa fa-trash-o"></i>
  <% end %>
<% end %>

app/views/layouts/aca_rails/_flash_messages.html.erb
<% flash.each do |type, message| %>
    <div class="alert <%= alert_class_for(type) %> alert-dismissible fade show alert-fixed" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= message %>
    </div>
<% end %>

app/views/layouts/aca_rails/_header.html.erb
<div class="form-element-align">
  <h1>
    <%= title %>
  </h1>
</div>

app/views/layouts/aca_rails/_navigation.html.erb
<nav class="navbar navbar-dark bg-dark navbar-expand-lg fixed-top">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <a class="navbar-brand" href="#"> <%= AcaRails.app_name %> </a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <%= render 'layouts/aca_rails/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/aca_rails/_navigation_links.html.erb
<li class="nav-item active">
  <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">Features</a>
</li>

<% if current_user %>
  <% if current_user.is_admin? %>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="AdminDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Administrate
      </a>
      <div class="dropdown-menu" aria-labelledby="AdminDropdown">
        <a class="dropdown-item" href="<%= users_path %>">User management</a>
        <a class="dropdown-item" href="<%= password_resets_path %>">Reset password</a>
        <a class="dropdown-item" href="#">Preferences</a>
      </div>
    </li>
  <% end %>
  <li class="nav-item dropdown" >
    <a class="nav-link dropdown-toggle" href="#" id="UserDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fa fa-user"></i> <%= current_user.name %>
    </a>
    <div class="dropdown-menu" aria-labelledby="UserDropdown">
      <a class="dropdown-item" href="<%= edit_changepwd_path(current_user.id) %>">Change password</a>
      <a class="dropdown-item" href="<%= edit_my_profile_path(current_user) %>">Profile</a>
      <% if AcaRails.user_can_inactivate_account || AcaRails.user_can_delete_account %>
        <a class="dropdown-item" href="<%= edit_inactivate_path(current_user) %>">Inactivate / remove account</a>
      <% end %>
    </div>
  </li>
  <li class="nav-item">
    <%= link_to logout_path, title: "Logout", data: { toggle: 'tooltip', placement: 'botton' }, :class => 'nav-link' do %>
      <i class="fa fa-sign-out"></i>
    <% end %>
  </li>
<% else %>
  <% if AcaRails.user_can_signup %>
    <li class="nav-item">
      <a class="nav-link" href="<%= signup_path %>">Sign Up</a>
    </li>
  <% end %>

  <li class="nav-item">
    <%= link_to login_path, title: "Login", data: { toggle: 'tooltip', placement: 'botton' }, :class => 'nav-link' do %>
      <i class="fa fa-sign-in"></i> Login
    <% end %>
  </li>
<% end %>

app/views/layouts/aca_rails/_tabs.html.erb
<!-- Tab menu-->
<%
  classe_index = classe_new = classe_edit = classe_show = classe_versions = classe_version = "nav-link"
  case action
    when "index"
      classe_index = "nav-link active"
    when "new"
      classe_new = "nav-link active"
    when "edit"
      classe_edit = "nav-link active"
    when "show"
      classe_show = "nav-link active"
    when "versions"
      classe_versions = "nav-link active"
    when "version"
      classe_version = "nav-link active"
  end
%>

<ul class="nav nav-tabs flex-wrap">
  <% if !defined?(abas) || abas.include?('index')%>
  <li class="nav-item" >
      <%= link_to "Index", {controller: controller_class , action: "index"}, class: classe_index %>
  </li>
  <% end %>
  <% if !defined?(abas) || abas.include?('new')%>
  <li class="nav-item" >
      <%= link_to "New", {controller: controller_class , action: "new"}, class: classe_new %>
  </li>
  <% end %>

  <% if !defined?(abas) || abas.include?('versions')%>
  <li class="nav-item" >
      <%= link_to "Versions",{controller: controller_class , action: "versions"}, class: classe_versions %>
  </li>
  <% end %>

  <% if action=="edit" || action=="show" || action=="version" %>
      <li class="nav-item">
        <%= link_to "Edit",{controller: controller_class , action: "edit"}, class: classe_edit %>
      </li>
      <li class="nav-item">
        <%= link_to "Show",{controller: controller_class , action: "show"}, class: classe_show %>
      </li>
      <li class="nav-item">
        <%= link_to "Version",{controller: controller_class , action: "version"}, class: classe_version %>
      </li>
  <% end %>


  <% if action=="index" %>

      <li class="nav-item ml-auto">
        <a class="nav-link" href="#AdvancedSearch" data-toggle="modal">Advanced Search</a>
      </li>

      <li class="nav-item">
      <%= search_form_for @q, :html => { :class => 'navbar-search form-inline float-right', :id => 'quick_search'}   do |f| %>
            <%= f.search_field search_field, :class => 'form-control', :placeholder => "Quick Search" %>

            <button type="button" class="close pl-1" aria-label="Close">
              <span aria-hidden="true"
                    onclick="document.getElementById('q_<%=search_field%>').value='';"
                    ondblclick="document.getElementById('q_<%=search_field%>').value='';
                        document.getElementById('quick_search').submit();">
                &times;
              </span>
            </button>
        <% end %>
      </li>
  <% end %>

  <% if action == "versions" %>
      <li class="nav-item  ml-auto">
        <%= search_form_for @q, url: versions_users_path, :html => { :class => 'navbar-search form-inline float-right', :id => 'quick_search'}   do |f| %>
            <%= f.search_field 'event_or_object_changes_cont', :class => 'form-control', :placeholder => "Quick Search" %>

            <button type="button" class="close pl-1" aria-label="Close">
              <span aria-hidden="true"
                    onclick="document.getElementById('q_event_or_object_changes_cont').value='';"
                    ondblclick="document.getElementById('q_event_or_object_changes_cont').value='';
                        document.getElementById('quick_search').submit();">
                &times;
              </span>
            </button>
        <% end %>
      </li>
  <% end %>

  <% if action == "version" %>
      <li class="nav-item  ml-auto">
        <%= search_form_for @q, url: version_user_path(params[:id]), :html => { :class => 'navbar-search form-inline float-right', :id => 'quick_search'}   do |f| %>
            <%= f.search_field 'event_or_object_changes_cont', :class => 'form-control', :placeholder => "Quick Search" %>
            <%= f.hidden_field :item_id_eq, value: params[:id]  %>
            <button type="button" class="close pl-1" aria-label="Close">
              <span aria-hidden="true"
                    onclick="document.getElementById('q_event_or_object_changes_cont').value='';"
                    ondblclick="document.getElementById('q_event_or_object_changes_cont').value='';
                        document.getElementById('quick_search').submit();">
                &times;
              </span>
            </button>
        <% end %>
      </li>
  <% end %>

</ul>
&nbsp;

app/views/layouts/aca_rails/_versions.html.erb
<!-- Versions table-->
<div class="table-responsive">
  <table class="table table-striped table-hover table-sm table-bordered">
    <thead>
    <tr>
      <th><%= sort_link @q, :id, "Id" %></th>
      <th><%= sort_link @q, :item_id, "Object Id" %></th>
      <th><%= sort_link @q, :event, "Event" %></th>
      <th><%= sort_link @q, :whodunnit, "Who" %></th>
      <th><%= sort_link @q, :created_at, "Date" %></th>
      <th>Change</th>
    </tr>
    </thead>
    <tbody>
    <% versions.each do |version| %>
        <tr>
          <td><%= version.id %></td>
          <td><%= version.item_id %></td>
          <td><%= version.event %></td>
          <td>
          <% begin %>
          <%= version.user %>
          <% rescue %>
          <%= version.whodunnit %>
          <% end %>
          </td>
          <td><%= version.created_at.strftime("%d/%m/%Y %H:%M") %></td>
          <td>
            <% version.changeset.each do |k,v| %>
                <%= k.humanize %>:&nbsp;
                <code><%= v[0]==nil ? "nil":v[0] %></code>
                &nbsp;=>&nbsp;
                <code><%= v[1]==nil ? "nil":v[1] %></code>
                <br>
            <% end %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <%= paginate versions, views_prefix: 'aca_rails' %>
</div>

app/views/layouts/aca_rails/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aca rails</title>
  <%= stylesheet_link_tag    "aca_rails/application", media: "all" %>
  <%= javascript_include_tag "aca_rails/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: 'layouts/aca_rails/navigation', flash: flash%>

<div class="container-fluid">

  <%= render partial: 'layouts/aca_rails/flash_messages', flash: flash%>

  <%= yield %>

  <div class="jumbotron">
    <%= debug(params) if Rails.env.development? %>
  </div>
</div>


</body>
</html>